name: 'Publish'

on:
  release:
    types:
      - published

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  release_zip_file:
    name: Publish integration zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3

      - name: Build Integration ZIP package
        run: |
          cd ${{ github.workspace }}/custom_components/econnect_metronet
          zip hacs_econnect_metronet.zip -r ./

      - name: Upload ZIP package release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ github.workspace }}/custom_components/econnect_metronet/hacs_econnect_metronet.zip
